Hacked the LVD test system a bit so that unit tests could be run in Windows unmanaged by a parent process.  Got the error 'fatal error C1128: number of sections exceeded object file format limit : compile with /bigobj' while trying to compile applications_test in MSVC.